# Generated by Django 3.0.3 on 2020-03-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Staff. Note: Is used IN ADDITION TO is_cleaner or is_investor'),
        ),
    ]
