# Generated by Django 3.0.3 on 2020-02-11 19:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNr', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Hotelroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(default=1)),
                ('numberOnFloor', models.IntegerField(default=1, validators=[django.core.validators.MinLengthValidator(2, message='Ensure numberOnFloor has two digits (00-99)'), django.core.validators.MaxLengthValidator(2, message='Ensure numberOnFloor has two digits (00-99)')])),
                ('singleBeds', models.IntegerField(default=0)),
                ('doubleBeds', models.IntegerField(default=0)),
                ('pricePrNight', models.IntegerField()),
                ('includedBreakfast', models.BooleanField(default=True)),
                ('includedParking', models.BooleanField(default=True)),
                ('includedCancelling', models.BooleanField(default=False)),
                ('smokingAllowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNr', models.CharField(max_length=8)),
                ('dateStart', models.DateField(verbose_name='Start date')),
                ('dateEnd', models.DateField(verbose_name='End date')),
                ('customerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.Customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.Hotelroom')),
            ],
        ),
    ]
