# Generated by Django 3.0.3 on 2020-03-16 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200212_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['dateStart', 'dateEnd', 'room']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['lastName', 'firstName']},
        ),
        migrations.AlterModelOptions(
            name='hotelroom',
            options={'ordering': ['roomNumber']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='customerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.Customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phoneNr',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
