# Generated by Django 3.0.3 on 2020-03-31 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200322_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='lastCleaned',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last cleaned'),
        ),
    ]
